version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: attendance-backend64
    ports:
      - "3021:3021"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=attendance_db
    volumes:
      - ./Backend:/app

  employee-attendance:
    build: ./Employee-Attendance
    container_name: attendance-employee64
    ports:
      - "8037:80"
    depends_on:
      - backend

  hr-attendance:
    build: ./HR-Attendance
    container_name: attendance-hr64
    ports:
      - "8038:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: attendance-db64
    ports:
      - "5416:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=attendance_db
    volumes:
      - pgdata64:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata64:

